theme: jekyll-theme-cayman
title: AfricaNLP Workshop
description: "Putting Africa on the NLP Map. ICLR 2020, Addis Ababa, Ethiopia"
basepath: ""


navigation:
- text: HOME
  url: /
- text: CALL FOR PAPERS
  url: /cfp.html
- text: DATES
  url: /dates.html
  layout: project
- text: PROGRAM
  url: /program.html
  layout: post
- text: ORGANIZERS
  url: /organizers.html  